"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gw.py']
DATA_FILES = ['layout.xml',
			'layout_details.xml',
			'layout_search.xml',
			'layout_songdb.xml',
			'layout_update.xml',
			#icons etc
			'gw.ico',
'graphics/applications-internet.png',
'graphics/checkmark.png',
'graphics/document-save.png',
'graphics/drive-harddisk-selected.png',
'graphics/drive-harddisk.png',
'graphics/edit-clear.png',
'graphics/edit-clear-small.png',
'graphics/emblem-favorite.png',
'graphics/emblem-unreadable.png',
'graphics/folder-saved-search.png',
'graphics/list-add.png',
'graphics/media-eject.png',
'graphics/media-playback-start.png',
'graphics/media-playback-stop.png',
'graphics/media-playback-pause.png',
'graphics/media-random-selected.png',
'graphics/media-random.png',
'graphics/media-record-hover.png',
'graphics/media-record-selected.png',
'graphics/media-record.png',
'graphics/media-repeat-selected-all.png',
'graphics/media-repeat-selected-one.png',
'graphics/media-repeat.png',
'graphics/media-skip-backward.png',
'graphics/media-skip-forward.png',
'graphics/no_cover.png',
'graphics/preferences-system.png',
'graphics/software-update-available.png',
'graphics/system-search.png',
'graphics/user-trash.png',
'graphics/arrow-down.png',
'graphics/list-add-all.png',
'graphics/weather-clear.png',
'graphics/weather-clear-night.png',
'graphics/weather-few-clouds.png',
'graphics/weather-overcast.png',
'graphics/weather-storm.png',
'locale/en_US/layout.mo',
'locale/en_US/layout.po',
'locale/es_AR/layout.mo',
'locale/es_AR/layout.po',
'locale/tr_TR/layout.mo',
'locale/tr_TR/layout.po',
'locale/layout.pot'
			]
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
